# fly.toml app configuration file generated for jainbot on 2023-08-27T11:53:21+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jainbot"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="jainbot_data"
  destination="./"